SELECT 
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT ui.USER_ID) AS USERS
FROM USER_INFO ui
    INNER JOIN ONLINE_SALE os ON ui.USER_ID = os.USER_ID
WHERE 
    GENDER IS NOT NULL
GROUP BY 
    YEAR,
    MONTH,
    GENDER
ORDER BY 
    YEAR,
    MONTH,
    GENDER