SELECT car.CAR_ID,
    car.CAR_TYPE,
    ROUND(DAILY_FEE * 30 * (1 - DISCOUNT_RATE / 100)) AS FEE
FROM (
        SELECT CAR_ID,
            CAR_TYPE,
            DAILY_FEE
        FROM CAR_RENTAL_COMPANY_CAR
        WHERE CAR_TYPE IN ('세단', 'SUV')
    ) car
    INNER JOIN (
        SELECT CAR_TYPE,
            SUBSTRING_INDEX(DISCOUNT_RATE, '%', 1) AS DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE DURATION_TYPE = '30일 이상'
    ) plan ON car.CAR_TYPE = plan.CAR_TYPE
WHERE CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE > '2022-11-00'
            AND START_DATE < '2022-12-00'
    )
GROUP BY FEE
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC,
    CAR_TYPE,
    CAR_ID DESC