WITH RECURSIVE EMPTY_HOUR as (
    SELECT 0 AS HOUR
    UNION
    SELECT HOUR + 1 AS HOUR
    FROM EMPTY_HOUR
    WHERE HOUR < 23
)
SELECT eh.HOUR,
    IFNULL(COUNT, 0) AS COUNT
FROM EMPTY_HOUR eh
    LEFT OUTER JOIN (
        SELECT HOUR(DATETIME) AS HOUR,
            COUNT(*) AS COUNT
        FROM ANIMAL_OUTS
        GROUP BY HOUR
    ) ao ON eh.HOUR = ao.HOUR
ORDER BY HOUR