SELECT 
    f.CATEGORY,
    MAX_PRICE,
    PRODUCT_NAME
FROM FOOD_PRODUCT f
    INNER JOIN (
        SELECT 
            CATEGORY,
            MAX(PRICE) AS MAX_PRICE
        FROM FOOD_PRODUCT
        WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
        GROUP BY CATEGORY ) t 
    ON f.CATEGORY = t.CATEGORY
        AND PRICE = MAX_PRICE
ORDER BY MAX_PRICE DESC