SELECT MEMBER_NAME,
    r.REVIEW_TEXT,
    DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE m
    INNER JOIN REST_REVIEW r ON m.MEMBER_ID = r.MEMBER_ID
    INNER JOIN (
        SELECT *
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1
    ) max_r ON r.MEMBER_ID = max_r.MEMBER_ID
ORDER BY REVIEW_DATE,
    REVIEW_TEXT