SELECT CATEGORY,
    SUM(SALES) AS TOTAL_SALES
FROM BOOK
    LEFT JOIN BOOK_SALES USING (BOOK_ID)
WHERE SALES_DATE >= '2022-01-01'
    AND SALES_DATE <= '2022-01-31'
GROUP BY CATEGORY
ORDER BY CATEGORY