SELECT HISTORY_ID,
    ROUND(
        DAILY_FEE * DIFF * (100 - IFNULL(DISCOUNT_RATE, 0)) / 100
    ) AS FEE
FROM CAR_RENTAL_COMPANY_CAR cc
    INNER JOIN (
        SELECT HISTORY_ID,
            CAR_ID,
            DATEDIFF(END_DATE, START_DATE) + 1 AS DIFF,
            CASE
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN NULL
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 30 THEN '7일 이상'
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 90 THEN '30일 이상'
                ELSE '90일 이상'
            END AS DURATION_TYPE
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ) ch ON cc.CAR_ID = ch.CAR_ID
    LEFT OUTER JOIN (
        SELECT DURATION_TYPE,
            SUBSTRING_INDEX(DISCOUNT_RATE, '%', 1) AS DISCOUNT_RATE,
            CAR_TYPE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    ) cp ON ch.DURATION_TYPE = cp.DURATION_TYPE
    AND cc.CAR_TYPE = cp.CAR_TYPE
WHERE cc.CAR_TYPE = '트럭'
ORDER BY FEE DESC,
    HISTORY_ID DESC