SELECT fp.PRODUCT_ID,
    PRODUCT_NAME,
    SUM(AMOUNT * PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT fp
    INNER JOIN FOOD_ORDER fr ON fp.PRODUCT_ID = fr.PRODUCT_ID
WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY fp.PRODUCT_ID
ORDER BY TOTAL_SALES DESC,
    PRODUCT_ID