SELECT DISTINCT c.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR c
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h ON c.CAR_ID = h.CAR_ID
WHERE CAR_TYPE = '세단'
    AND START_DATE >= '2022-10-01'
ORDER BY CAR_ID DESC